name: jwt-decode
summary: jwt decode tool
description: >
        A command line tool to decode JWT tokens.

        **Commands:**

        Header decode
        `jwt-decode.header 'JWT TOKEN HERE'`

        Payload decode
        `jwt-decode.payload 'JWT TOKEN HERE'`
version: '1.0'
license: MIT

base: core18
grade: stable
confinement: strict

parts:
  script:
    source: .
    plugin: dump
    organize:
      jwtDecode: jwtDecode.sh
  jq:
    source: .
    plugin: nil
    stage-packages: [jq]

apps:
  payload:
    command: /bin/sh $SNAP/jwtDecode.sh 2

  header:
    command: /bin/sh $SNAP/jwtDecode.sh 1 
